### ISSUE TITLE
[Request] Config option to allow spawn eggs and/or commands

### ISSUE THREAD

**Issue by chimericdream** [nvb-uy/YSNS-Legacy#1]
I'd love to prevent all natural spawning of certain mobs, but allow them to be spawned in via commands or spawn eggs. Would it be possible to make this a config option for the mod?

**Comment by nvb-uy** [comment]
Feel free to contribute! ^^ I may add it in the future but currently I'm busy with many projects

**Comment by nvb-uy** [comment]
Moved to another repo
https://github.com/nvb-uy/YSNS/issues
