### ISSUE TITLE
YSNS config crashing modded 1.20.1 Minecraft [fabric]

### ISSUE THREAD

**Issue by EevyernDracaneon** [nvb-uy/YSNS-Legacy#10]
before i added the updated config into the config folder my modpack loaded up completely fine, as long as no mobs were blacklisted. i tested ysns on its own yesterday to see if it worked in 1.20.1 and to figure out how to make it work and it didn't crash. removing the config additions made minecraft stop crashing

here's the code in case i somehow messed something up? if it was a me problem that'd be predictable, im new to this stuff but i followed the guide and even used the summon command in game to get the exact letters (dunno why its formatted weird, this is my first time submitting smth like this, its formatted fine in my notepad)

{
  "blacklisted_entities": [
    "any_mod:example_entity",
    "minecraft:guardian"
	"minecraft:elder_guardian"
	"betternether:hydrogen_jellyfish"
	"betternether:jungle_skeleton"
	"betternether:naga"
	"mythicmounts:geckotoalizard"
	"mythicmounts:netherbat"
	"mythicmounts:nightmare"
	"naturalist:firefly"
	"naturalist:snail"
	"promenade:lush_creeper"
	"clutter:capybara"
	"spawn:snail"
  ]
}

and my crash log if that'll help

[latest.log](https://github.com/nvb-uy/YSNS/files/13642261/latest.log)

**Comment by nvb-uy** [comment]
You have to add a comma after each entry except the last, like this:

{
"blacklisted_entities": [
"any_mod:example_entity",
"minecraft:guardian",
"minecraft:elder_guardian",
"betternether:hydrogen_jellyfish",
"betternether:jungle_skeleton",
"betternether:naga",
"mythicmounts:geckotoalizard",
"mythicmounts:netherbat",
"mythicmounts:nightmare",
"naturalist:firefly",
"naturalist:snail",
"promenade:lush_creeper",
"clutter:capybara",
"spawn:snail"
]
}
