### ISSUE TITLE
Spawns not being disabled at all

### ISSUE THREAD

**Issue by Artha-Demon** [nvb-uy/YSNS-Legacy#11]
I have silverfish disabled because their very existence pisses me off to no end. They aren't challenging, they are just fucking annoying when they constantly spawn while just generally mining. I hate them. Hate. Same with Vexes. Vexes as a mob actively make Minecraft a worse game by existing.

There's a few mods that have mobs I HATE (The stupid fanmade enderman from Farlanders can die in a chemical fire, Alex's Mobs Murmur is irritating, the skeleton creeper from Graveyard spawns WAY too much and I hate the thing, and screw cave spiders, like, seriously. The poison effect is SO annoying. SO. ANNOYING) and they are still spawning, even after making sure the config was done right. 

Is there something I'm doing wrong?

![image](https://github.com/nvb-uy/YSNS/assets/46292432/1f2a56d9-18f4-4d11-86f7-a90d77b0c7ba)

That is how I have it set up

This is for Forge 1.20.1

**Comment by dxdvostfr** [comment]
same issue here

**Comment by DexterWard9** [comment]
Same issue: I have Forge 1.18.2 instance with quite a few mods. Blacklisted only the Creeper to test - Creepers still spawn. Created a test instance: Forge 40.2.17, MC 1.18.2 ; Mods: You Shall Not Spawn 1.0.2, Xaero's Minimap 23.9.3, Xaero's World Map 1.37.3 - Same issue. Edit the ysns.json in the config file just blacklisting the Creeper, and Creepers still spawn.

Doesn't work in 1.19.2 with same setup either.

**Comment by Wordshere** [comment]
Try adding a space between switching to different mods.

**Comment by theJarl99** [comment]
> Try adding a space between switching to different mods.

don't think that makes a difference. ive run into the same issue with testing the mod on 1.20.1 and it's not even preventing spawns with vanilla mobs (no other mods interfering so it's no mod incompat). either there's something we're not doing right in the config or the mod is bugged. will try testing with older versions.

**Comment by Merancapeman** [comment]
This... just doesn't work for 1.20.1. Not even a little bit. Going to try Spawn Balance Utility.

**Comment by RealHypnoticOcelot** [comment]
Also having issues with this, on Forge 1.20.1. This is the only mod to disable spawning on Modrinth, so it's a big issue.

**Comment by grahamfoxrollup** [comment]
same issue with special golems mod, the glacial golems refuse to not spawn. YSNS doesnt work

**Comment by Java-Fish** [comment]
Apparently the problem still exists. I actually wanted to prevent vanilla mobs from spawning since I want to play Cobblemon, but my config doesn't seem to be working. Is there a solution yet?
`{
  "rules": [
    {
      "name": "Block All Vanilla Monsters",
      "criteria": [
        {
          "type": "entity",
          "entity_type": "minecraft:zombie"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:skeleton"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:creeper"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:spider"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:enderman"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:cave_spider"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:witch"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:slime"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:ghast"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:magma_cube"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:blaze"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:zombie_pigman"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:phantom"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:drowned"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:husk"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:stray"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:guardian"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:elder_guardian"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:vex"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:vindicator"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:evoker"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:ravager"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:pillager"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:illusioner"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:shulker"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:silverfish"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:endermite"
        }
      ],
      "block": true
    },
    {
      "name": "Block All Vanilla Animals",
      "criteria": [
        {
          "type": "entity",
          "entity_type": "minecraft:cow"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:pig"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:sheep"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:chicken"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:rabbit"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:horse"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:donkey"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:llama"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:polar_bear"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:parrot"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:ocelot"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:wolf"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:fox"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:bat"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:panda"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:mooshroom"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:bee"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:goat"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:axolotl"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:glow_squid"
        }
      ],
      "block": true
    },
    {
      "name": "Allow Villagers and Wandering Trader",
      "criteria": [
        {
          "type": "entity",
          "entity_type": "minecraft:villager"
        },
        {
          "type": "entity",
          "entity_type": "minecraft:wandering_trader"
        }
      ],
      "block": false
    }
  ]
}
`

**Comment by alarmgoose** [comment]
Same issue here. Everything I put in the config still spawns.

**Comment by trashraccoon42** [comment]
If this mod has an issue where the only thing it is intended to do is not working, it should probably be temporarily made private or at least have some disclaimer on curseforge, otherwise its going to continue to waste a lot of people's time which could easily be prevented

**Comment by trashraccoon42** [comment]
same issue for forge 1.20.1

**Comment by alarmgoose** [comment]
> same issue for forge 1.20.1

Does the dev check here? It seems like a lot of people are having the same issue. D=

**Comment by trashraccoon42** [comment]
really wish this issue would be fixed

**Comment by nvb-uy** [comment]
Fixed in v2.0.0

P.S. Moved to another repo
https://github.com/nvb-uy/YSNS/issues
