### ISSUE TITLE
The dretched beasts still resides in 1.19.2 (resolved)

### ISSUE THREAD

**Issue by Wordshere** [nvb-uy/YSNS-Legacy#12]
Version 1.19.2 CurseForge Modloader Forge Version 43.3.0
I'm using YSNS-FFQ-1.0.2.jar and I also loaded it with 1.0.1
Mobs I've blacklisted still spawn. I reinstalled it on a fresh modpack with just the mod monsters I wanted (ryan's zombies, conrad's spiders). I also made sure I changed the values as soon as the config folder generated on the modpack and before starting the game or creating the world.
![Ysns](https://github.com/nvb-uy/YSNS/assets/107021299/7006c4bc-0972-4bbe-968a-4334a9544e3c)
sorry for the large image I have a weird screen resolution.
![Pest](https://github.com/nvb-uy/YSNS/assets/107021299/35718698-91aa-4141-9c5d-e700788e75f9)

**Comment by Wordshere** [comment]
I think it's just a 1.19.2 thing, try using Bad Mobs Mod for 1.19.2 specific packs. Leaving this for 1.19.2 users in case the creators decide to focus on the new releases instead, that being said I do love YSNS. Have a good day. :)

**Comment by theJarl99** [comment]
> I think it's just a 1.19.2 thing, try using Bad Mobs Mod for 1.19.2 specific packs. Leaving this for 1.19.2 users in case the creators decide to focus on the new releases instead, that being said I do love YSNS. Have a good day. :)

it's not. im on 1.20.1 and running into the same issue. Bad Mobs only works for vanilla mobs too fyi, at least I don't see any options to prevent spawns from modded entities with that one :/

**Comment by ArkenorOakshadow** [comment]
I'm on 20.1 too, and trying to turn the mana and artifice mobs off for a bit as they tend to take over the spawn table with no way to change their weight. Try as I might, they will not go away.

**Comment by nvb-uy** [comment]
Fixed in v2.0.0

P.S. Moved to another repo
https://github.com/nvb-uy/YSNS/issues
