### ISSUE TITLE
Possible Bug: Mobs spawned prior to blacklisting get despawned

### ISSUE THREAD

**Issue by ValokAsura** [nvb-uy/YSNS-Legacy#14]
Thank you for the mod! I have a minor issue I wanted to mention.

The FAQ for your mod on Modrinth states:

"What if I add an entity to blacklist that was already spawned? Spawned entities will still exist, so it's up to you if you want to kill them or not."

I had a named endermite at my enderman farm and it was loaded into a minecart. Days later, I added endermite to to my YSNS blacklist so I could use enderpearls without worrying about those stupid little guys spawning. Unfortunately, it caused my named endermite in the end to despawn, so I had to remove it from the blacklist in order to fix my farm.

I just wanted to let you know that the either the FAQ is incorrect, or the mod might not be working properly (or I might just be a dummy).

Thank you for your time!

**Comment by nvb-uy** [comment]
Fixed in v2.0.0

P.S. Moved to another repo
https://github.com/nvb-uy/YSNS/issues
