### ISSUE TITLE
Initializing game crash

### ISSUE THREAD

**Issue by samve000** [nvb-uy/YSNS-Legacy#15]
When I edit the ysns.json file to add a mob to it, the game crashes.
[crash-2024-07-17_15.59.57-client.txt](https://github.com/user-attachments/files/16266697/crash-2024-07-17_15.59.57-client.txt)
[ysns.json](https://github.com/user-attachments/files/16266720/ysns.json)

**Comment by ValokAsura** [comment]
It looks like you have some syntax problems. You're missing a comma after "any_mod:another_example_entity" as well as the closing bracket. Try this:

[ysns.json](https://github.com/user-attachments/files/16325949/ysns.json)

**Comment by samve000** [comment]
Just realized it myself but thanks!
