### ISSUE TITLE
Still Spawning Naturally

### ISSUE THREAD

**Issue by TheSnipps** [nvb-uy/YSNS-Legacy#3]
Hello, I am on 1.19.4 fabric and all mobs added to the blacklist are still spawning naturally in my worlds.  It works with spawn eggs/commands/etc, however naturally they are still spawning.

**Comment by nvb-uy** [comment]
Are you using the latest version?

**Comment by TheSnipps** [comment]
Looks like I wasn't, got the newest version and it's working.  Thanks!
