### ISSUE TITLE
issues with 1.0.2 and 1.0.3

### ISSUE THREAD

**Issue by Zygus42** [nvb-uy/YSNS-Legacy#4]
1.0.3 with forge 1.19.4 does not start up (even with no other mods installed), with the message: failed to load correctly.
[debug.log](https://github.com/nvb-uy/YSNS/files/11601442/debug.log)

1.0.2 with forge 1.194 runs fine (with lots of mods installed), but running a server with it, Pillager towers are still spawning Pillagers etc.  Config is set up as:
{
  "blacklisted_entities": [
    "minecraft:pillager",
    "minecraft:illusioner",
    "minecraft:evoker",
    "minecraft:ravager",
    "minecraft:vindicator"
  ]
}

Any clues as to why ?

**Comment by sebix123456** [comment]
same issue. I keep blacklisting mobs in singleplayer and nothing changes
did i write somthing wrong?
{
  "blacklisted_entities": [
    "minecraft:spider",
    "minecraft:skeleton",
    "minecraft:creeper",
    "minecraft:witch"
  ]
}

**Comment by nvb-uy** [comment]
Fixed in latest version, an outdated version was present in some platforms.
