### ISSUE TITLE
Request for config help

### ISSUE THREAD

**Issue by supaflange** [nvb-uy/YSNS-Legacy#5]
Thanks for your work on the mod. Much appreciated. 

I edited the json as follows but still getting the mob spawning, even in new world gens. Am I doing something wrong?

{
  "blacklisted_entities": [
    "minecraft:zombie",
    "minecraft:witch",
    "minecraft:skeleton",
    "minecraft:vex",
    "minecraft:husk",
  ]
}

**Comment by nvb-uy** [comment]
Remove the last comma, commas are only needed when there's another entry afterwards.

This is to report issues with the mod, for help, please ask in https://lunapixel.studio/discord in the #elocins-projects channel

**Comment by supaflange** [comment]
Thanks. I removed the comma, and rebooted, but still getting those mobs spawning. I also noticed something in the log saying the spawn values were readjusted. i'll try to recreate share those lines.
