### ISSUE TITLE
I blacklisted all evil/bad mobs but still get 1 that spawns

### ISSUE THREAD

**Issue by Beerandoo** [nvb-uy/YSNS-Legacy#6]
I banned zombies yet i still see baby zombies on a chicken being spawned why is this and how do i fix it? This is the config I have: {
  "blacklisted_entities": [
"minecraft:zombie",
"minecraft:skeleton",
"minecraft:creeper",
"minecraft:stray",
"minecraft:slime",
"minecraft:ender_dragon",
"minecraft:enderman",
"minecraft:cave_spider",
"minecraft:spider",
"minecraft:blaze",
"minecraft:spider",
"minecraft:drowned",
"minecraft:elder_guardian",
"minecraft:evoker",
"minecraft:ghast",
"minecraft:guardian",
"minecraft:hoglin",
"minecraft:husk",
"minecraft:magma_cube",
"minecraft:phantom",
"minecraft:piglin",
"minecraft:piglin_brute",
"minecraft:pillager",
"minecraft:ravager",
"minecraft:shulker",
"minecraft:silverfish",
"minecraft:endermite",
"minecraft:vex",
"minecraft:vindicator",
"minecraft:warden",
"minecraft:witch",
"minecraft:wither_skeleton",
"minecraft:wither",
"minecraft:zoglin",
"minecraft:zombie_villager",
"minecraft:zombified_piglin",
"minecraft:magma_cube",

    "any_mod:example_entity",
    "any_mod:another_example_entity"
  ]
}

any help would be appreciated thankyou

**Comment by Beerandoo** [comment]
Has there been any update to fix this? I keep getting baby zombies soanwing on top of chickens and sometimes illagers spawning aswell, when they are already blacklisted as shown above.

**Comment by nvb-uy** [comment]
Sadly as of now they do spawn because they don't spawn alone but rather on top of an entity, which YSNS doesn't yet detect
