### ISSUE TITLE
the configuracion doesnt change anything

### ISSUE THREAD

**Issue by sebix123456** [nvb-uy/YSNS-Legacy#7]
I'm playing on forge 1.0.2 version and whatever I type nothing changes. there is no never version for forge 1.19
My config.
{
"blacklisted_entities": [
"minecraft:spider",
"minecraft:skeleton",
"minecraft:creeper",
"minecraft:witch"
]
}

what am I doing wrong?

**Comment by nvb-uy** [comment]
Fixed in latest version, an outdated version was present in some platforms.
