### ISSUE TITLE
Invisible mobs when generating new chunks until rejoining the world

### ISSUE THREAD

**Issue by Mig979** [nvb-uy/YSNS-Legacy#8]
Minecraft 1.19.2
Fabric version 0.14.22
YSNS version 1.0.3

I've blacklisted every vanilla mob and I can hear animals walking around and doing their sounds even though I can't see them. I've even had an invisible chicken pop out an egg which I could pick up and I have also had a constant bee popping in and out of a beehive sound even though there's no bee to be seen and when I say constant I mean like multiple of these sounds per second not in a normal vanilla manner. 

I can't spawn any of the mobs with spawn eggs so it seems to be working as intended but I'm thinking it has to do with mobs spawned at chunk creation? Upon rejoining my world all of these invisible entities seem to disappear but it's a rather annoying issue that I have to keep quitting and joining the world to get rid of them when that's the whole point of the mod.

If you're wondering why I wanted to remove all mobs it's because I'm playing with Cobblemon and I wanted to find only Pokemon and not vanilla mobs which break my immersion lol.

**Comment by DayBreakShifter** [comment]
Same thing here. The beehives in particular are just generating massive amounts of noise whenever I'm nearby.

**Comment by nvb-uy** [comment]
Something is likely modifying the serverworld's addEntity method, will look into it

**Comment by nvb-uy** [comment]
Fixed in v2.0.0

P.S. Moved to another repo
https://github.com/nvb-uy/YSNS/issues
