### ISSUE TITLE
Not working at all in 1.20.1

### ISSUE THREAD

**Issue by Zygus42** [nvb-uy/YSNS-Legacy#9]
Contents of ysns.json:
{
  "blacklisted_entities": [
    "minecraft:pillager"
  ]
}

Pillagers are spawning just fine - pillager outposts are filled with them, and if you clear the outpost, continue to spawn no problems at all.  F3 identifies entities as "minecraft:pillager".

Any clues as to why this is not working ?

**Comment by VoxelHeart** [comment]
I'm having the same issue. I've put in most vanilla minecraft mobs and it doesn't seem to work.

**Comment by rheena211** [comment]
Not working at all in 1.19.2

**Comment by nvb-uy** [comment]
Fixed in latest version, an outdated version was present in some platforms.
